# Generated by Django 5.1.2 on 2025-01-30 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_traveltip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traveltip',
            name='long_description',
        ),
    ]
