# Generated by Django 5.1.2 on 2025-01-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_traveltip_long_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveltip',
            name='long_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='place',
            name='long_description',
            field=models.TextField(default='No description available'),
        ),
        migrations.AlterField(
            model_name='traveltip',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='traveltips/'),
        ),
    ]
