# Generated by Django 5.1.2 on 2025-02-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_traveltip_long_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveltip',
            name='long_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='traveltip',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
