# Generated by Django 5.1.2 on 2025-02-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_place_show_on_homepage_alter_image_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='destinations/')),
                ('short_description', models.TextField()),
                ('long_description', models.TextField()),
            ],
        ),
    ]
